### ISSUE TITLE
Controller中的返回类型异常

### ISSUE THREAD

**Issue by gelald** [201206030/novel-cloud#7]
在master分支中，部分Controller的某些方法所定义的返回类型(ResultBean)中显式地指定了泛型的具体类型，导致代码有语法错误。
![image](https://user-images.githubusercontent.com/37375083/127738618-12ba5c04-8932-4960-8d6b-9c222e1553e1.png)

**Comment by 201206030** [comment]
重新更新一下代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月31日(周六) 晚上7:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [201206030/novel-cloud] Controller中的返回类型异常 (#7)




 
在master分支中，部分Controller的某些方法所定义的返回类型(ResultBean)中显式地指定了泛型的具体类型，导致代码有语法错误。
